### ISSUE TITLE
Release tarballs cannot be built

### ISSUE THREAD

**Issue by rmustacc** [joyent/mdb_v8#56]
The tarballs that represent a given release cannot build because they don't include the private copy of libavl. You end up getting: 

```
git submodule update --init deps/illumos-libavl
error: pathspec 'mdb_v8/mdb_v8-1.1.2-32/deps/illumos-libavl' did not match any file(s) known to git.
Did you forget to 'git add'?
Makefile.targ:159: recipe for target 'deps/illumos-libavl/.git' failed
```

It's not clear if they were intended to be used or not (github just made them available).

**Comment by davepacheco** [comment]
Where did this tarball come from?  I don't know anything about it, and it's not something the mdb_v8 project itself provides.  I tried the Github-provided tarball from https://github.com/joyent/mdb_v8/tarball/v1.1.2, but that does not include any git information in it (which probably makes sense):

```
$ curl -OL https://github.com/joyent/mdb_v8/tarball/v1.1.2
$ tar xzf v1.1.2
$ ls
total 248
drwxr-xr-x  17 dap  staff     578 Nov 12 20:59 joyent-mdb_v8-295949f/
-rw-r--r--   1 dap  staff  126259 Feb 29 11:45 v1.1.2
$ cd joyent-mdb_v8-295949f/
$ ls -a .git
ls: .git: No such file or directory
$ git submodule update --init deps/illumos-libavl
fatal: Not a git repository (or any of the parent directories): .git
```

I think you got a different, confusing error message because your parent directory is a git repo.

I don't think it can be supported to build a release from the Github-provided tarballs (for the reason you mentioned).  The better way to do this is to clone the repo, checkout the release's tag, and build it normally.  If it's useful to have proper release tarballs, we can build those as part of the release process and upload them somewhere.  I'm going to close this, but we can reopen as an RFE if that would be useful.

If I misunderstood and you're referring to some other tarball, let me know.
